apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
      - backend:
          serviceName: {{ .Chart.Name }}
          servicePort: {{ .Values.service.port }}
